steps:
  - id: build-docker-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--tag=gcr.io/$PROJECT_ID/apps/hello-cje"
      - .
images:
  - "gcr.io/$PROJECT_ID/apps/hello-cje"
